import { Transaction } from "./transaction-detail-drawer";

export const mockTransactions = [
  // 2023 Transactions
  {
    id: 1,
    description: "Monthly Salary - Dean of Engineering",
    amount: 45000,
    type: "income",
    date: "2023-01-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 2,
    description: "ACH Payment - Virtual Assistant Services",
    amount: -3800,
    type: "expense",
    date: "2023-01-20",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 3,
    description: "Web Development Project - Enterprise Platform",
    amount: 85000,
    type: "income",
    date: "2023-01-25",
    merchant: "Fortune 500 Tech Client",
  },
  {
    id: 4,
    description: "ACH Payment - Senior Web Developer",
    amount: -5200,
    type: "expense",
    date: "2023-01-28",
    merchant: "James Chen - Lead Developer",
  },
  {
    id: 5,
    description: "Real Estate Commission - Luxury Estate Sale",
    amount: 250000,
    type: "income",
    date: "2023-02-05",
    merchant: "Sotheby's International Realty",
  },
  {
    id: 6,
    description: "ACH Payment - Property Manager",
    amount: -4500,
    type: "expense",
    date: "2023-02-10",
    merchant: "David Rodriguez - Property Management",
  },
  {
    id: 7,
    description: "Monthly Salary - Dean of Engineering",
    amount: 45000,
    type: "income",
    date: "2023-02-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 8,
    description: "ACH Payment - Real Estate Marketing Team",
    amount: -6000,
    type: "expense",
    date: "2023-02-18",
    merchant: "Emily Johnson - Marketing Coordinator",
  },
  {
    id: 9,
    description: "Consulting - AI/ML Implementation",
    amount: 120000,
    type: "income",
    date: "2023-02-28",
    merchant: "Tech Consulting - Enterprise Client",
  },
  {
    id: 10,
    description: "ACH Payment - Technical Writer",
    amount: -3900,
    type: "expense",
    date: "2023-03-05",
    merchant: "Michael Thompson - Documentation Specialist",
  },
  {
    id: 11,
    description: "Monthly Salary - Dean of Engineering",
    amount: 45000,
    type: "income",
    date: "2023-03-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 12,
    description: "Real Estate Commission - Commercial Property",
    amount: 180000,
    type: "income",
    date: "2023-03-20",
    merchant: "CBRE Luxury Properties",
  },
  {
    id: 13,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2023-03-25",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 14,
    description: "ACH Payment - SEO & Digital Marketing",
    amount: -5500,
    type: "expense",
    date: "2023-03-30",
    merchant: "Robert Kim - Marketing Consultant",
  },
  {
    id: 15,
    description: "Monthly Salary - Dean of Engineering",
    amount: 45000,
    type: "income",
    date: "2023-04-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 16,
    description: "Web Development - SaaS Platform",
    amount: 95000,
    type: "income",
    date: "2023-04-18",
    merchant: "Silicon Valley Startup",
  },
  {
    id: 17,
    description: "ACH Payment - Frontend Developer",
    amount: -4800,
    type: "expense",
    date: "2023-04-22",
    merchant: "Lisa Wang - React Specialist",
  },
  {
    id: 18,
    description: "Real Estate Commission - Penthouse Sale",
    amount: 320000,
    type: "income",
    date: "2023-05-08",
    merchant: "Douglas Elliman Real Estate",
  },
  {
    id: 19,
    description: "ACH Payment - Property Stager",
    amount: -3200,
    type: "expense",
    date: "2023-05-12",
    merchant: "Amanda Foster - Staging Services",
  },
  {
    id: 20,
    description: "Monthly Salary - Dean of Engineering",
    amount: 45000,
    type: "income",
    date: "2023-05-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 21,
    description: "ACH Payment - Backend Developer",
    amount: -5800,
    type: "expense",
    date: "2023-05-20",
    merchant: "Carlos Mendez - Backend Engineer",
  },
  {
    id: 22,
    description: "Web Development - Blockchain Project",
    amount: 150000,
    type: "income",
    date: "2023-05-28",
    merchant: "Crypto Finance Platform",
  },
  {
    id: 23,
    description: "ACH Payment - UI/UX Designer",
    amount: -4200,
    type: "expense",
    date: "2023-06-05",
    merchant: "Jennifer Lee - UX Designer",
  },
  {
    id: 24,
    description: "Monthly Salary - Dean of Engineering",
    amount: 45000,
    type: "income",
    date: "2023-06-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 25,
    description: "Real Estate Commission - Investment Portfolio",
    amount: 275000,
    type: "income",
    date: "2023-06-20",
    merchant: "Christie's International Real Estate",
  },
  {
    id: 26,
    description: "ACH Payment - Real Estate Attorney",
    amount: -6000,
    type: "expense",
    date: "2023-06-25",
    merchant: "Patricia Williams - Legal Services",
  },
  {
    id: 27,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2023-06-30",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 28,
    description: "Summer Teaching - Executive MBA Program",
    amount: 35000,
    type: "income",
    date: "2023-07-10",
    merchant: "Harvard Business School",
  },
  {
    id: 29,
    description: "Monthly Salary - Dean of Engineering",
    amount: 45000,
    type: "income",
    date: "2023-07-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 30,
    description: "Web Development - FinTech Application",
    amount: 110000,
    type: "income",
    date: "2023-07-20",
    merchant: "Global Banking Corp",
  },
  {
    id: 31,
    description: "ACH Payment - DevOps Engineer",
    amount: -5400,
    type: "expense",
    date: "2023-07-25",
    merchant: "Thomas Anderson - DevOps Specialist",
  },
  {
    id: 32,
    description: "ACH Payment - Content Marketing",
    amount: -4100,
    type: "expense",
    date: "2023-07-30",
    merchant: "Michelle Park - Content Strategist",
  },
  {
    id: 33,
    description: "Real Estate Commission - Waterfront Property",
    amount: 290000,
    type: "income",
    date: "2023-08-05",
    merchant: "Compass Real Estate",
  },
  {
    id: 34,
    description: "Monthly Salary - Dean of Engineering",
    amount: 45000,
    type: "income",
    date: "2023-08-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 35,
    description: "ACH Payment - Property Inspector",
    amount: -3500,
    type: "expense",
    date: "2023-08-20",
    merchant: "David Rodriguez - Home Inspector",
  },
  {
    id: 36,
    description: "Consulting - Cloud Architecture",
    amount: 98000,
    type: "income",
    date: "2023-08-28",
    merchant: "Enterprise Tech Solutions",
  },
  {
    id: 37,
    description: "ACH Payment - Social Media Manager",
    amount: -4600,
    type: "expense",
    date: "2023-09-05",
    merchant: "Brandon Scott - Social Media Specialist",
  },
  {
    id: 38,
    description: "Monthly Salary - Dean of Engineering",
    amount: 45000,
    type: "income",
    date: "2023-09-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 39,
    description: "Real Estate Commission - Multi-Unit Complex",
    amount: 425000,
    type: "income",
    date: "2023-09-22",
    merchant: "Keller Williams Luxury Estates",
  },
  {
    id: 40,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2023-09-28",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 41,
    description: "Web Development - AI Integration",
    amount: 135000,
    type: "income",
    date: "2023-09-30",
    merchant: "Machine Learning Startup",
  },
  {
    id: 42,
    description: "ACH Payment - Full Stack Developer",
    amount: -5900,
    type: "expense",
    date: "2023-10-05",
    merchant: "Alex Johnson - Full Stack Engineer",
  },
  {
    id: 43,
    description: "Monthly Salary - Dean of Engineering",
    amount: 45000,
    type: "income",
    date: "2023-10-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 44,
    description: "ACH Payment - Real Estate Photographer",
    amount: -3300,
    type: "expense",
    date: "2023-10-20",
    merchant: "Emily Johnson - Luxury Photography",
  },
  {
    id: 45,
    description: "Research Grant - AI Ethics Program",
    amount: 75000,
    type: "income",
    date: "2023-10-25",
    merchant: "National Science Foundation",
  },
  {
    id: 46,
    description: "Real Estate Commission - Office Building",
    amount: 380000,
    type: "income",
    date: "2023-11-02",
    merchant: "JLL Commercial Real Estate",
  },
  {
    id: 47,
    description: "ACH Payment - Bookkeeper",
    amount: -4200,
    type: "expense",
    date: "2023-11-08",
    merchant: "Rachel Green - Accounting Services",
  },
  {
    id: 48,
    description: "Monthly Salary - Dean of Engineering",
    amount: 45000,
    type: "income",
    date: "2023-11-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 49,
    description: "Web Development - Mobile App",
    amount: 125000,
    type: "income",
    date: "2023-11-20",
    merchant: "Healthcare Tech Company",
  },
  {
    id: 50,
    description: "ACH Payment - Mobile Developer",
    amount: -5300,
    type: "expense",
    date: "2023-11-25",
    merchant: "Nina Patel - iOS Developer",
  },
  {
    id: 51,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2023-11-30",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 52,
    description: "Real Estate Commission - Luxury Condo",
    amount: 195000,
    type: "income",
    date: "2023-12-05",
    merchant: "Coldwell Banker Premier",
  },
  {
    id: 53,
    description: "Monthly Salary - Dean of Engineering",
    amount: 45000,
    type: "income",
    date: "2023-12-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 54,
    description: "ACH Payment - Legal Services",
    amount: -6000,
    type: "expense",
    date: "2023-12-18",
    merchant: "Patricia Williams - Real Estate Attorney",
  },
  {
    id: 55,
    description: "Consulting - Digital Transformation",
    amount: 145000,
    type: "income",
    date: "2023-12-22",
    merchant: "Fortune 100 Consulting Project",
  },
  {
    id: 56,
    description: "ACH Payment - Project Manager",
    amount: -5100,
    type: "expense",
    date: "2023-12-28",
    merchant: "Kevin Martinez - Project Coordinator",
  },
  // 2024 Transactions
  {
    id: 57,
    description: "Monthly Salary - Dean of Engineering",
    amount: 47000,
    type: "income",
    date: "2024-01-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 58,
    description: "Real Estate Commission - Estate Sale",
    amount: 340000,
    type: "income",
    date: "2024-01-20",
    merchant: "Sotheby's International Realty",
  },
  {
    id: 59,
    description: "ACH Payment - Marketing Coordinator",
    amount: -4800,
    type: "expense",
    date: "2024-01-25",
    merchant: "Michelle Park - Marketing Services",
  },
  {
    id: 60,
    description: "Web Development - E-learning Platform",
    amount: 115000,
    type: "income",
    date: "2024-01-30",
    merchant: "EdTech Innovation Corp",
  },
  {
    id: 61,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2024-02-05",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 62,
    description: "Monthly Salary - Dean of Engineering",
    amount: 47000,
    type: "income",
    date: "2024-02-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 63,
    description: "ACH Payment - Database Administrator",
    amount: -5600,
    type: "expense",
    date: "2024-02-20",
    merchant: "Daniel Wong - Database Specialist",
  },
  {
    id: 64,
    description: "Real Estate Commission - Commercial Lease",
    amount: 225000,
    type: "income",
    date: "2024-02-28",
    merchant: "CBRE Commercial Real Estate",
  },
  {
    id: 65,
    description: "ACH Payment - Graphic Designer",
    amount: -4400,
    type: "expense",
    date: "2024-03-05",
    merchant: "Sophia Chen - Creative Services",
  },
  {
    id: 66,
    description: "Monthly Salary - Dean of Engineering",
    amount: 47000,
    type: "income",
    date: "2024-03-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 67,
    description: "Web Development - Custom CRM",
    amount: 155000,
    type: "income",
    date: "2024-03-20",
    merchant: "Real Estate Software Client",
  },
  {
    id: 68,
    description: "ACH Payment - QA Tester",
    amount: -4700,
    type: "expense",
    date: "2024-03-25",
    merchant: "Marcus Brown - Quality Assurance",
  },
  {
    id: 69,
    description: "Real Estate Commission - Investment Property",
    amount: 285000,
    type: "income",
    date: "2024-03-30",
    merchant: "Douglas Elliman Real Estate",
  },
  {
    id: 70,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2024-04-05",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 71,
    description: "Monthly Salary - Dean of Engineering",
    amount: 47000,
    type: "income",
    date: "2024-04-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 72,
    description: "ACH Payment - Real Estate Analyst",
    amount: -5200,
    type: "expense",
    date: "2024-04-20",
    merchant: "Gregory Taylor - Market Analyst",
  },
  {
    id: 73,
    description: "Consulting - Cybersecurity Assessment",
    amount: 98000,
    type: "income",
    date: "2024-04-28",
    merchant: "Financial Services Security",
  },
  {
    id: 74,
    description: "Real Estate Commission - Luxury Home",
    amount: 395000,
    type: "income",
    date: "2024-05-05",
    merchant: "Christie's International Real Estate",
  },
  {
    id: 75,
    description: "Monthly Salary - Dean of Engineering",
    amount: 47000,
    type: "income",
    date: "2024-05-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 76,
    description: "ACH Payment - Video Editor",
    amount: -3900,
    type: "expense",
    date: "2024-05-20",
    merchant: "Tyler Johnson - Video Production",
  },
  {
    id: 77,
    description: "Web Development - API Development",
    amount: 88000,
    type: "income",
    date: "2024-05-28",
    merchant: "Cloud Services Provider",
  },
  {
    id: 78,
    description: "ACH Payment - Technical Writer",
    amount: -4300,
    type: "expense",
    date: "2024-06-05",
    merchant: "Michael Thompson - Documentation",
  },
  {
    id: 79,
    description: "Monthly Salary - Dean of Engineering",
    amount: 47000,
    type: "income",
    date: "2024-06-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 80,
    description: "Real Estate Commission - Portfolio Sale",
    amount: 520000,
    type: "income",
    date: "2024-06-20",
    merchant: "Compass Real Estate",
  },
  {
    id: 81,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2024-06-25",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 82,
    description: "ACH Payment - SEO Specialist",
    amount: -5500,
    type: "expense",
    date: "2024-06-30",
    merchant: "Robert Kim - SEO Services",
  },
  {
    id: 83,
    description: "Summer Teaching - Tech Leadership",
    amount: 38000,
    type: "income",
    date: "2024-07-10",
    merchant: "Stanford Graduate School of Business",
  },
  {
    id: 84,
    description: "Monthly Salary - Dean of Engineering",
    amount: 47000,
    type: "income",
    date: "2024-07-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 85,
    description: "Web Development - Blockchain Platform",
    amount: 175000,
    type: "income",
    date: "2024-07-22",
    merchant: "DeFi Technology Group",
  },
  {
    id: 86,
    description: "ACH Payment - Smart Contract Developer",
    amount: -6000,
    type: "expense",
    date: "2024-07-28",
    merchant: "Olivia Martinez - Blockchain Developer",
  },
  {
    id: 87,
    description: "Real Estate Commission - Commercial Building",
    amount: 465000,
    type: "income",
    date: "2024-08-05",
    merchant: "JLL Commercial Properties",
  },
  {
    id: 88,
    description: "ACH Payment - Property Manager",
    amount: -4900,
    type: "expense",
    date: "2024-08-12",
    merchant: "David Rodriguez - Property Services",
  },
  {
    id: 89,
    description: "Monthly Salary - Dean of Engineering",
    amount: 47000,
    type: "income",
    date: "2024-08-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 90,
    description: "ACH Payment - Frontend Developer",
    amount: -5400,
    type: "expense",
    date: "2024-08-20",
    merchant: "Lisa Wang - React Developer",
  },
  {
    id: 91,
    description: "Consulting - AI Strategy",
    amount: 125000,
    type: "income",
    date: "2024-08-30",
    merchant: "Tech Venture Capital Firm",
  },
  {
    id: 92,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2024-09-05",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 93,
    description: "Monthly Salary - Dean of Engineering",
    amount: 47000,
    type: "income",
    date: "2024-09-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 94,
    description: "Real Estate Commission - Penthouse",
    amount: 380000,
    type: "income",
    date: "2024-09-20",
    merchant: "Sotheby's International Realty",
  },
  {
    id: 95,
    description: "ACH Payment - Copywriter",
    amount: -4100,
    type: "expense",
    date: "2024-09-25",
    merchant: "Jessica Adams - Content Writer",
  },
  {
    id: 96,
    description: "Web Development - Enterprise Dashboard",
    amount: 142000,
    type: "income",
    date: "2024-09-30",
    merchant: "Data Analytics Corporation",
  },
  {
    id: 97,
    description: "ACH Payment - UI Designer",
    amount: -4800,
    type: "expense",
    date: "2024-10-05",
    merchant: "Jennifer Lee - Interface Design",
  },
  {
    id: 98,
    description: "Monthly Salary - Dean of Engineering",
    amount: 47000,
    type: "income",
    date: "2024-10-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 99,
    description: "Real Estate Commission - Retail Space",
    amount: 295000,
    type: "income",
    date: "2024-10-22",
    merchant: "CBRE Retail Properties",
  },
  {
    id: 100,
    description: "ACH Payment - Systems Architect",
    amount: -5900,
    type: "expense",
    date: "2024-10-28",
    merchant: "Andrew Wilson - Systems Design",
  },
  {
    id: 101,
    description: "Research Grant - Machine Learning",
    amount: 85000,
    type: "income",
    date: "2024-10-30",
    merchant: "Department of Defense Research",
  },
  {
    id: 102,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2024-11-05",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 103,
    description: "Monthly Salary - Dean of Engineering",
    amount: 47000,
    type: "income",
    date: "2024-11-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 104,
    description: "Web Development - SaaS Solution",
    amount: 165000,
    type: "income",
    date: "2024-11-20",
    merchant: "PropTech Innovation Inc",
  },
  {
    id: 105,
    description: "ACH Payment - Cloud Engineer",
    amount: -5700,
    type: "expense",
    date: "2024-11-25",
    merchant: "Thomas Anderson - AWS Specialist",
  },
  {
    id: 106,
    description: "Real Estate Commission - Waterfront Estate",
    amount: 575000,
    type: "income",
    date: "2024-11-30",
    merchant: "Douglas Elliman Luxury Division",
  },
  {
    id: 107,
    description: "ACH Payment - Bookkeeper",
    amount: -4400,
    type: "expense",
    date: "2024-12-05",
    merchant: "Rachel Green - Financial Services",
  },
  {
    id: 108,
    description: "Monthly Salary - Dean of Engineering",
    amount: 47000,
    type: "income",
    date: "2024-12-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 109,
    description: "Consulting - Technology Roadmap",
    amount: 135000,
    type: "income",
    date: "2024-12-20",
    merchant: "Global Investment Bank",
  },
  {
    id: 110,
    description: "ACH Payment - Legal Services",
    amount: -6000,
    type: "expense",
    date: "2024-12-28",
    merchant: "Patricia Williams - Attorney",
  },
  // 2025 Transactions
  {
    id: 111,
    description: "Monthly Salary - Dean of Engineering",
    amount: 48500,
    type: "income",
    date: "2025-01-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 112,
    description: "Real Estate Commission - Multi-Family Property",
    amount: 485000,
    type: "income",
    date: "2025-01-20",
    merchant: "Keller Williams Commercial",
  },
  {
    id: 113,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2025-01-25",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 114,
    description: "Web Development - AI-Powered App",
    amount: 195000,
    type: "income",
    date: "2025-01-30",
    merchant: "Artificial Intelligence Startup",
  },
  {
    id: 115,
    description: "ACH Payment - ML Engineer",
    amount: -6200,
    type: "expense",
    date: "2025-02-05",
    merchant: "Nathan Kumar - Machine Learning",
  },
  {
    id: 116,
    description: "Monthly Salary - Dean of Engineering",
    amount: 48500,
    type: "income",
    date: "2025-02-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 117,
    description: "Real Estate Commission - Office Complex",
    amount: 625000,
    type: "income",
    date: "2025-02-22",
    merchant: "Cushman & Wakefield",
  },
  {
    id: 118,
    description: "ACH Payment - Marketing Manager",
    amount: -5100,
    type: "expense",
    date: "2025-02-28",
    merchant: "Michelle Park - Marketing Lead",
  },
  {
    id: 119,
    description: "Consulting - Digital Infrastructure",
    amount: 155000,
    type: "income",
    date: "2025-03-05",
    merchant: "Multinational Corporation",
  },
  {
    id: 120,
    description: "ACH Payment - Data Scientist",
    amount: -5800,
    type: "expense",
    date: "2025-03-10",
    merchant: "Victoria Zhang - Data Analytics",
  },
  {
    id: 121,
    description: "Monthly Salary - Dean of Engineering",
    amount: 48500,
    type: "income",
    date: "2025-03-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 122,
    description: "Web Development - Fintech Platform",
    amount: 185000,
    type: "income",
    date: "2025-03-22",
    merchant: "Digital Banking Innovators",
  },
  {
    id: 123,
    description: "ACH Payment - Backend Engineer",
    amount: -5600,
    type: "expense",
    date: "2025-03-28",
    merchant: "Carlos Mendez - API Development",
  },
  {
    id: 124,
    description: "Real Estate Commission - Luxury Penthouse",
    amount: 540000,
    type: "income",
    date: "2025-03-30",
    merchant: "Christie's International Real Estate",
  },
  {
    id: 125,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2025-04-05",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 126,
    description: "Monthly Salary - Dean of Engineering",
    amount: 48500,
    type: "income",
    date: "2025-04-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 127,
    description: "ACH Payment - Property Stager",
    amount: -3600,
    type: "expense",
    date: "2025-04-20",
    merchant: "Amanda Foster - Staging Services",
  },
  {
    id: 128,
    description: "Web Development - Healthcare Portal",
    amount: 128000,
    type: "income",
    date: "2025-04-28",
    merchant: "Medical Technology Group",
  },
  {
    id: 129,
    description: "Real Estate Commission - Commercial Lease",
    amount: 365000,
    type: "income",
    date: "2025-05-05",
    merchant: "JLL Corporate Solutions",
  },
  {
    id: 130,
    description: "ACH Payment - Drone Photographer",
    amount: -4200,
    type: "expense",
    date: "2025-05-10",
    merchant: "Marcus Reed - Aerial Photography",
  },
  {
    id: 131,
    description: "Monthly Salary - Dean of Engineering",
    amount: 48500,
    type: "income",
    date: "2025-05-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 132,
    description: "ACH Payment - SEO Consultant",
    amount: -5300,
    type: "expense",
    date: "2025-05-20",
    merchant: "Robert Kim - Digital Marketing",
  },
  {
    id: 133,
    description: "Consulting - Enterprise Architecture",
    amount: 142000,
    type: "income",
    date: "2025-05-28",
    merchant: "Fortune 500 Tech Consulting",
  },
  {
    id: 134,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2025-06-05",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 135,
    description: "Monthly Salary - Dean of Engineering",
    amount: 48500,
    type: "income",
    date: "2025-06-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 136,
    description: "Real Estate Commission - Estate Portfolio",
    amount: 725000,
    type: "income",
    date: "2025-06-20",
    merchant: "Sotheby's International Realty",
  },
  {
    id: 137,
    description: "ACH Payment - Videographer",
    amount: -4500,
    type: "expense",
    date: "2025-06-25",
    merchant: "Tyler Johnson - Video Production",
  },
  {
    id: 138,
    description: "Web Development - Quantum Computing UI",
    amount: 215000,
    type: "income",
    date: "2025-06-30",
    merchant: "Quantum Systems Laboratory",
  },
  {
    id: 139,
    description: "ACH Payment - Security Specialist",
    amount: -5900,
    type: "expense",
    date: "2025-07-05",
    merchant: "Derek Phillips - Cybersecurity",
  },
  {
    id: 140,
    description: "Summer Teaching - Innovation Workshop",
    amount: 42000,
    type: "income",
    date: "2025-07-10",
    merchant: "Wharton School of Business",
  },
  {
    id: 141,
    description: "Monthly Salary - Dean of Engineering",
    amount: 48500,
    type: "income",
    date: "2025-07-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 142,
    description: "Real Estate Commission - Resort Property",
    amount: 595000,
    type: "income",
    date: "2025-07-22",
    merchant: "Compass Luxury Estates",
  },
  {
    id: 143,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2025-07-28",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 144,
    description: "ACH Payment - 3D Rendering Artist",
    amount: -5100,
    type: "expense",
    date: "2025-07-30",
    merchant: "Isabella Garcia - Architectural Rendering",
  },
  {
    id: 145,
    description: "Web Development - IoT Dashboard",
    amount: 165000,
    type: "income",
    date: "2025-08-05",
    merchant: "Smart Home Technology Inc",
  },
  {
    id: 146,
    description: "ACH Payment - Mobile Developer",
    amount: -5700,
    type: "expense",
    date: "2025-08-10",
    merchant: "Nina Patel - Mobile Apps",
  },
  {
    id: 147,
    description: "Monthly Salary - Dean of Engineering",
    amount: 48500,
    type: "income",
    date: "2025-08-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 148,
    description: "Real Estate Commission - Investment Fund Properties",
    amount: 840000,
    type: "income",
    date: "2025-08-22",
    merchant: "CBRE Investment Properties",
  },
  {
    id: 149,
    description: "ACH Payment - Brand Designer",
    amount: -4900,
    type: "expense",
    date: "2025-08-28",
    merchant: "Sophia Chen - Brand Identity",
  },
  {
    id: 150,
    description: "Consulting - AI Ethics Framework",
    amount: 175000,
    type: "income",
    date: "2025-08-30",
    merchant: "Global Tech Policy Institute",
  },
  {
    id: 151,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2025-09-05",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 152,
    description: "Monthly Salary - Dean of Engineering",
    amount: 48500,
    type: "income",
    date: "2025-09-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 153,
    description: "Web Development - Metaverse Platform",
    amount: 235000,
    type: "income",
    date: "2025-09-20",
    merchant: "VR Innovation Labs",
  },
  {
    id: 154,
    description: "ACH Payment - VR Developer",
    amount: -6200,
    type: "expense",
    date: "2025-09-25",
    merchant: "Ethan Cooper - Virtual Reality",
  },
  {
    id: 155,
    description: "Real Estate Commission - Hotel Property",
    amount: 975000,
    type: "income",
    date: "2025-09-30",
    merchant: "Colliers International",
  },
  {
    id: 156,
    description: "ACH Payment - Property Lawyer",
    amount: -6000,
    type: "expense",
    date: "2025-10-05",
    merchant: "Patricia Williams - Legal Counsel",
  },
  {
    id: 157,
    description: "Research Grant - Quantum AI",
    amount: 95000,
    type: "income",
    date: "2025-10-10",
    merchant: "DARPA Research Initiative",
  },
  {
    id: 158,
    description: "Monthly Salary - Dean of Engineering",
    amount: 48500,
    type: "income",
    date: "2025-10-15",
    merchant: "Massachusetts Institute of Technology",
  },
  {
    id: 159,
    description: "ACH Payment - Business Analyst",
    amount: -5400,
    type: "expense",
    date: "2025-10-20",
    merchant: "Gregory Taylor - Market Analysis",
  },
  {
    id: 160,
    description: "Web Development - Trading Platform",
    amount: 198000,
    type: "income",
    date: "2025-10-28",
    merchant: "Algorithmic Trading Corp",
  },
  {
    id: 161,
    description: "ACH Payment - Virtual Assistant",
    amount: -3800,
    type: "expense",
    date: "2025-10-30",
    merchant: "Sarah Martinez - Contract Worker",
  },
  {
    id: 162,
    description: "Real Estate Commission - Mixed-Use Development",
    amount: 685000,
    type: "income",
    date: "2025-11-05",
    merchant: "Douglas Elliman Development",
  },
  {
    id: 163,
    description: "ACH Payment - Social Media Strategist",
    amount: -4700,
    type: "expense",
    date: "2025-11-08",
    merchant: "Brandon Scott - Social Strategy",
  },
  {
    id: 164,
    description: "Monthly Salary - Dean of Engineering",
    amount: 48500,
    type: "income",
    date: "2025-11-12",
    merchant: "Massachusetts Institute of Technology",
  },
].reverse() as Transaction[];
