import { Transaction } from "./transaction-detail-drawer";

export const mockTransactions = [
  {
    id: 1,
    description: "Direct Deposit - Executive Compensation",
    amount: 560000,
    type: "income",
    date: "2024-11-30",
    merchant: "DeltaTech Solutions Inc.",
  },
  {
    id: 2,
    description: "Organic Gourmet Market Purchase",
    amount: -11845,
    type: "expense",
    date: "2024-12-02",
    merchant: "Whole Foods Market, Austin TX",
  },
  {
    id: 3,
    description: "Mansion Rent Payment",
    amount: -185000,
    type: "expense",
    date: "2024-12-03",
    merchant: "Greystone Estates",
  },
  {
    id: 4,
    description: "Premium Streaming Subscription",
    amount: -1599,
    type: "expense",
    date: "2024-12-05",
    merchant: "Netflix",
  },
  {
    id: 5,
    description: "Estate Utility Bill",
    amount: -14236,
    type: "expense",
    date: "2024-12-07",
    merchant: "Austin Energy",
  },
  {
    id: 6,
    description: "Executive Salary Deposit",
    amount: 560000,
    type: "income",
    date: "2025-01-30",
    merchant: "DeltaTech Solutions Inc.",
  },
  {
    id: 7,
    description: "Luxury Grocery Store",
    amount: -9312,
    type: "expense",
    date: "2025-02-02",
    merchant: "H-E-B, Austin TX",
  },
  {
    id: 8,
    description: "Gourmet Lunch",
    amount: -1374,
    type: "expense",
    date: "2025-02-05",
    merchant: "Chick-fil-A, Research Blvd",
  },
  {
    id: 9,
    description: "High-Speed Internet Bill",
    amount: -6999,
    type: "expense",
    date: "2025-02-10",
    merchant: "Spectrum Internet",
  },
  {
    id: 10,
    description: "Transfer to Investment Portfolio",
    amount: -40000,
    type: "expense",
    date: "2025-02-12",
    merchant: "Capital One Wealth Management",
  },
  {
    id: 11,
    description: "High-End Freelance Payment - Web Design",
    amount: 95000,
    type: "income",
    date: "2025-02-16",
    merchant: "Upwork Client - Horizon Media LLC",
  },
  {
    id: 12,
    description: "Mansion Rent Payment",
    amount: -185000,
    type: "expense",
    date: "2025-02-28",
    merchant: "Greystone Estates",
  },
  {
    id: 13,
    description: "Direct Deposit - Executive Salary",
    amount: 565000,
    type: "income",
    date: "2025-03-01",
    merchant: "DeltaTech Solutions Inc.",
  },
  {
    id: 14,
    description: "Premium Fuel Station",
    amount: -5462,
    type: "expense",
    date: "2025-03-04",
    merchant: "Shell, Round Rock TX",
  },
  {
    id: 15,
    description: "Luxury Electronics Purchase",
    amount: -21689,
    type: "expense",
    date: "2025-03-09",
    merchant: "Amazon.com",
  },
  {
    id: 16,
    description: "Premium Freelance Payment - App UI Design",
    amount: 130000,
    type: "income",
    date: "2025-03-21",
    merchant: "Fiverr Client - LunaTech Labs",
  },
  {
    id: 17,
    description: "Fine Dining Dinner",
    amount: -7421,
    type: "expense",
    date: "2025-03-23",
    merchant: "Cheesecake Factory, Austin TX",
  },
  {
    id: 18,
    description: "Mansion Rent Payment",
    amount: -185000,
    type: "expense",
    date: "2025-03-30",
    merchant: "Greystone Estates",
  },
  {
    id: 19,
    description: "Executive Salary Deposit",
    amount: 570000,
    type: "income",
    date: "2025-04-01",
    merchant: "DeltaTech Solutions Inc.",
  },
  {
    id: 20,
    description: "Private Car Service Ride",
    amount: -2855,
    type: "expense",
    date: "2025-04-03",
    merchant: "Uber Black",
  },
  {
    id: 21,
    description: "Premium Music Subscription",
    amount: -1099,
    type: "expense",
    date: "2025-04-04",
    merchant: "Apple Services",
  },
  {
    id: 22,
    description: "Luxury Grocery",
    amount: -13287,
    type: "expense",
    date: "2025-04-07",
    merchant: "H-E-B, Round Rock TX",
  },
  {
    id: 23,
    description: "High-Value Freelance - Backend API",
    amount: 210000,
    type: "income",
    date: "2025-05-11",
    merchant: "Freelancer.com Client - BrightApps LLC",
  },
  {
    id: 24,
    description: "Luxury Mortgage Payment",
    amount: -185000,
    type: "expense",
    date: "2025-05-30",
    merchant: "Wells Fargo Private Mortgage",
  },
  {
    id: 25,
    description: "Direct Deposit - Executive Salary",
    amount: 575000,
    type: "income",
    date: "2025-05-31",
    merchant: "DeltaTech Solutions Inc.",
  },
  {
    id: 26,
    description: "Designer Retail Purchase",
    amount: -8640,
    type: "expense",
    date: "2025-06-02",
    merchant: "Target, Austin TX",
  },
  {
    id: 27,
    description: "Premium Audio Subscription",
    amount: -999,
    type: "expense",
    date: "2025-06-05",
    merchant: "Spotify USA",
  },
  {
    id: 28,
    description: "Transfer to Offshore Investment",
    amount: -50000,
    type: "expense",
    date: "2025-07-01",
    merchant: "Capital One Wealth Management",
  },
  {
    id: 29,
    description: "Executive Salary Deposit",
    amount: 575000,
    type: "income",
    date: "2025-07-01",
    merchant: "DeltaTech Solutions Inc.",
  },
  {
    id: 30,
    description: "Artisanal Coffee",
    amount: -875,
    type: "expense",
    date: "2025-07-03",
    merchant: "Starbucks Reserve, Domain Northside",
  },
  {
    id: 31,
    description: "Premium Tech Accessory",
    amount: -4999,
    type: "expense",
    date: "2025-07-12",
    merchant: "Best Buy, Austin TX",
  },
  {
    id: 32,
    description: "Estate Rent Payment",
    amount: -185000,
    type: "expense",
    date: "2025-07-30",
    merchant: "Greystone Estates",
  },
  {
    id: 33,
    description: "Enterprise Freelance - Fullstack App",
    amount: 260000,
    type: "income",
    date: "2025-08-05",
    merchant: "Upwork Client - Nova Interactive",
  },
  {
    id: 34,
    description: "Executive Salary Deposit",
    amount: 575000,
    type: "income",
    date: "2025-08-30",
    merchant: "DeltaTech Solutions Inc.",
  },
  {
    id: 35,
    description: "Platinum Credit Card Payment",
    amount: -45000,
    type: "expense",
    date: "2025-09-03",
    merchant: "Chase Sapphire Reserve",
  },
  {
    id: 36,
    description: "Premium Grocery Store",
    amount: -10233,
    type: "expense",
    date: "2025-09-07",
    merchant: "Whole Foods Market, Austin TX",
  },
  {
    id: 37,
    description: "Executive Salary Deposit",
    amount: 580000,
    type: "income",
    date: "2025-09-30",
    merchant: "DeltaTech Solutions Inc.",
  },
  {
    id: 38,
    description: "Private Chauffeur Service",
    amount: -2210,
    type: "expense",
    date: "2025-10-04",
    merchant: "Uber Black",
  },
  {
    id: 39,
    description: "Strategic Freelance - API Integration",
    amount: 145000,
    type: "income",
    date: "2025-10-18",
    merchant: "Upwork Client - BluePeak Systems",
  },
  {
    id: 40,
    description: "Executive Salary Deposit",
    amount: 580000,
    type: "income",
    date: "2025-10-31",
    merchant: "DeltaTech Solutions Inc.",
  },
  {
    id: 41,
    description: "Michelin-Star Dinner",
    amount: -6578,
    type: "expense",
    date: "2025-11-02",
    merchant: "Texas Roadhouse Elite, Round Rock TX",
  },
  {
    id: 42,
    description: "Reserve Coffee Experience",
    amount: -655,
    type: "expense",
    date: "2025-11-03",
    merchant: "Starbucks Reserve, Arboretum Blvd",
  },
  {
    id: 43,
    description: "Private Banking Withdrawal",
    amount: -20000,
    type: "expense",
    date: "2025-11-04",
    merchant: "Chase Private Client ATM",
  },
].reverse() as Transaction[];
